# Generated by Django 2.0.5 on 2018-08-07 10:25

import ckeditor_uploader.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('decription', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('dateSubmit', models.DateField(default=datetime.date.today, verbose_name='date published')),
                ('view', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carid', models.CharField(max_length=50)),
                ('nameofcar', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('typecar', models.CharField(max_length=15)),
                ('yearofmanu', models.CharField(max_length=15)),
                ('avatar', models.ImageField(blank=True, default='car-icon.png', upload_to='avatar/')),
                ('locate_code', models.CharField(default='', max_length=50)),
                ('about_car', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=5000)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carservice.Blog')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='avatar/car.jpg', upload_to='avatar/')),
                ('title', models.CharField(max_length=200)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(default='nhanknth@gmail.com', max_length=254)),
                ('link', models.CharField(max_length=200)),
                ('summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('spent_oil', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('spent_steersman', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('spent_arises', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cName', models.CharField(max_length=50)),
                ('cAvatar', models.ImageField(blank=True, default='thumbnail.jpg', upload_to='avatar/')),
                ('cPhone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('cAddress', models.CharField(blank=True, max_length=100)),
                ('cID', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcard', models.CharField(max_length=10)),
                ('drivername', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('introduce', models.CharField(max_length=1000)),
                ('birthday', models.DateField()),
                ('experience', models.IntegerField()),
                ('avatar', models.ImageField(default='thumbnail.jpg', null=True, upload_to='avatar/')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_img', models.FileField(blank=True, default='thumbnail.jpg', upload_to='travel/')),
                ('comment_img', models.CharField(max_length=200)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carservice.Album')),
            ],
        ),
        migrations.CreateModel(
            name='RandomID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_day', models.DateField(verbose_name='date published')),
                ('destination_day', models.DateField(verbose_name='date published')),
                ('departure', models.CharField(max_length=500)),
                ('destination', models.CharField(max_length=500)),
                ('departure_time', models.TimeField(verbose_name='date published')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField(default=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carservice.Car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carservice.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='TypeNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='cost',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carservice.Schedule'),
        ),
        migrations.AddField(
            model_name='comment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carservice.Customer'),
        ),
        migrations.AddField(
            model_name='blog',
            name='typenews',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carservice.TypeNews'),
        ),
    ]
